plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.146'
}
version = mod_version
group = 'andrews.online_detector'
base { archivesName = 'online_detector' }
java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}
neoForge {
    version = neo_version
    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'online_detector'
        }
    }
    mods {
        online_detector { sourceSet(sourceSets.main) }
    }
}
var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [mod_version: mod_version, neo_version: neo_version]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.named('jar', Jar) {
    exclude 'andrews/online_detector/gametest/**', 'data/online_detector/structure/empty.nbt'
    from(files('LICENSE.txt', 'COPYING', 'NOTICE.md')) { into 'META-INF' }
}
