modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/tilosophy/OnlineDetector-NeoForge/issues"
[[mods]]
modId="online_detector"
version="${mod_version}"
displayName="Online Detector (NeoForge)"
authors="andrew0030; NeoForge port maintained by tilosophy"
logoFile="logo.png"
description='''Unofficial NeoForge port of Online Detector. Detect a player's online status with redstone.'''
[[dependencies.online_detector]]
modId="neoforge"
type="required"
versionRange="[${neo_version},21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.online_detector]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
